### ISSUE TITLE
About aggregate evaluation

### ISSUE THREAD

**Issue by ftgreat** [Zyphra/Zyda_processing#4]
Thanks for your great paper.
One question about aggregate evaluation, why metrics like MMLU are not included in aggregate evaluation?

**Comment by yury-tokpanov** [comment]
We do MMLU evaluation for our Zamba model: https://huggingface.co/Zyphra/Zamba-7B-v1 .

For the dataset ablations we performed the same evaluations as Dolma and Refinedweb for comparison purposes.
